#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 获取当前分支
current_branch=$(git rev-parse --abbrev-ref HEAD)

# 尝试获取目标分支
if git rev-parse --verify MERGE_HEAD &> /dev/null; then
  target_branch=$(git rev-parse --abbrev-ref @{u})
  source_branch=$(git rev-parse --abbrev-ref $(git merge-base HEAD MERGE_HEAD))
else
  target_branch="N/A"
  source_branch="N/A"
fi

echo -e "\033[33m -------------------  当前分支: $current_branch 正在对提交的代码执行操作 -------------------- \033[0m"
echo -e "\033[33m -------------------  当前合并分支: $source_branch 正在对提交的代码执行操作 -------------------- \033[0m"

# 如果是尝试将test分支合并到其他分支，则阻止该操作
if [ "$current_branch" != "test" ] && [ "$target_branch" = "test" ]; then
  echo "Cannot merge test branch into another branch."
  exit 1
fi

exit 0
