#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# 获取当前分支
currBranch=$(git rev-parse --abbrev-ref HEAD)
mergedList=$(git branch --merged $currBranch)


echo -e "\033[0;32m -------------------  当前分支: \033[33m $currBranch \033[0;32m 正在对提交的代码执行merge操作 --------------------"


# 将合并列表按行读取到数组中
IFS=$'\n' read -d '' -ra array <<< "$mergedList"

# 定义要搜索的分支名称
search="test"
found=false

# 遍历合并列表，检查是否存在 test 分支
for item in "${array[@]}"; do
    item_without_spaces=${item//[[:space:]]/}
    echo -e "\033[0;32m ------------------- $item_without_spaces --------------------"

    if [[ "$item_without_spaces" == "$search" ]]; then
        found=true
        break
    fi
done

# 如果是尝试将test分支合并到其他分支，则阻止该操作
if $found; then
    echo  "\033[33m 当前分支 \033[0;32m  $currBranch  包含了 \033[0;31m $search 分支合并记录"
    echo "\033[0;31m test禁止合并到其他分支"

    exit 1
fi

exit 0
