#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# 获取当前分支
current_branch=$(git rev-parse --abbrev-ref HEAD)

# 获取目标分支
if git rev-parse --verify MERGE_HEAD &> /dev/null; then
  target_branch=$(git rev-parse --abbrev-ref $(git rev-parse --verify MERGE_HEAD))
else
  target_branch="N/A"
fi

echo -e "\033[33m -------------------  当前分支: $current_branch 正在对提交的代码执行操作 -------------------- \033[0m"
echo -e "\033[33m -------------------  目标分支: $target_branch 正在对提交的代码执行操作 -------------------- \033[0m"

# 如果是尝试将 test 分支合并到其他分支，则阻止该操作
if [ "$current_branch" != "test" ] && [ "$target_branch" = "test" ]; then
  echo "Cannot merge from test branch to $target_branch."
  exit 1
fi


# 检查是否有待提交的文件
if [ -z "$(git diff --cached --name-only)" ]; then
  echo "No files to commit."
  exit 0
fi

npx --no-install lint-staged

# 运行 ESLint 进行静态代码分析
echo "Running ESLint..."
npx eslint --cache --fix $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')
if [ $? -ne 0 ]; then
  echo "ESLint found issues. Please fix them before committing."
  exit 1
fi

# 运行 Prettier 进行代码格式化
# echo "Running Prettier..."
# npx prettier --write $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx|json|css|scss|md)$')
# if [ $? -ne 0 ]; then
#   echo "Prettier found issues. Please fix them before committing."
#   exit 1
# fi

# 添加格式化后的文件到暂存区
git add $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx|json|css|scss|md)$')

# 检查是否存在冲突文件
conflict_files=$(git ls-files -u | cut -f2 | sort -u)
if [ -n "$conflict_files" ]; then
  echo "存在未解决的冲突文件，不能提交。请先解决冲突。"
  exit 1
fi

# 运行 Jest 单元测试
echo "Running Jest tests..."
npx jest --passWithNoTests
if [ $? -ne 0 ]; then
  echo "Some tests failed. Please fix them before committing."
  exit 1
fi

echo "全部提交..."
exit 0

npm run lint-staged
