#!/bin/sh

# 获取当前分支
currBranch=$(git rev-parse --abbrev-ref HEAD)
mergedList=$(git branch --merged $currBranch)

IFS=$'\n' read -d '' -ra array <<< "$mergedList"

search="test"
found=false

for item in "${array[@]}"; do
    item_without_spaces=${item//[[:space:]]/}
    if [[ "$item_without_spaces" == "$search" ]]; then
        found=true
        break
    fi
done

# 如果是尝试将test分支合并到其他分支，则阻止该操作
if $found; then
    echo  "\033[33m 当前分支 \033[0;32m  $currBranch  包含了 \033[0;31m $search 分支合并记录"
    echo "\033[0;31m test禁止合并到其他分支"

    exit 1
fi

exit 0
